# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  app:
    image: maxiplux/fastapidevops-auth:d023c0ef764e86dc827cceff0f626fccc49e6363
    container_name: app
    restart: on-failure
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD =postgres
      $FLAG_DB_HOST
      - DB_NAME=postgres
    ports:
      - 0.0.0.0:8080:80
  front-end:
    image: maxiplux/front-end:27cc05c45be0c7c12b593f599ef922aca735085b
    container_name: front-end
    restart: on-failure
    depends_on:
      - app
    ports:
      - 0.0.0.0:80:80
volumes:
  cache:
    driver: local
networks:
  dockernet:
    external: true
